### ISSUE TITLE
Super! iOS?

### ISSUE THREAD

**Issue by Noitidart** [MrPistoul/react-native-android-badger#1]
This is superb, is there plans for iOS support?

**Comment by MrPistoul** [comment]
IOS natively supports Badge.
See https://facebook.github.io/react-native/docs/pushnotificationios.html
Just import {PushNotificationIOS} from 'react-native'
or https://github.com/evollu/react-native-fcm if you use firebase for your notification.

**Comment by Noitidart** [comment]
Oooo thank you!!!
